name: CI
permissions:
  contents: read
on:
  push:
  pull_request:

jobs:
  check:
    name: Lint, Format, Typecheck and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
          submodules: true

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271
        with:
          version: 11.18.0

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm ci

      - name: Typecheck
        run: pnpm typecheck

      - name: Check
        run: pnpm lint

      - name: Run Tests
        run: pnpm test
